### ISSUE TITLE
Not working with Statamic 2.6.9

### ISSUE THREAD

**Issue by cibgraphics** [mwesten/StatamicV2-Highlight-Addon#1]
![screen shot 2017-09-28 at 4 58 30 pm](https://user-images.githubusercontent.com/972737/30993900-578b943c-a46e-11e7-85e6-a1bd3acd0e10.png)
![screen shot 2017-09-28 at 4 58 46 pm](https://user-images.githubusercontent.com/972737/30993906-5a0a5ee6-a46e-11e7-85f5-5113bf0a1ec7.png)

I have permissions set to 777.

**Comment by mwesten** [comment]
Hi Christopher,

Could you give me a bit more background information?
New install or upgrade? Did it work before?
Currently you show network/server/permission errors.

what happens if you try to access the css file from the `highlightjs` folder directly from your browser? ie: constructing the url yourself and putting it in your webbrowser?

**Comment by cibgraphics** [comment]
This is a new install on both the plugin side as well as the CMS.

When trying to go to the URL directly I get a 
```
Forbidden
You don't have permission to access /site/addons/Highlight/highlightjs/styles/monokai.css on this server.
```

Folder and Contents are 777 permissions.

**Comment by cibgraphics** [comment]
Any update? I would really love to get this working.

**Comment by cibgraphics** [comment]
I just integrated with the official plugin via JS. But seeing how I couldn't get this to work correctly is concerning.

**Comment by mwesten** [comment]
Hmmm looking into it now.... has to do with some api-changes in Statamic....

**Comment by mwesten** [comment]
Updated the code; should work now!
Also updated to the latest Highlight.js version.
